sudo: false
cache:
  directories:
  - "$HOME/.m2"
language: java
jdk:
  - oraclejdk8
script: mvn clean test
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  app: fb-messenger-chatbot
  api_key:
    secure: XdU0Bkksbwy8dxRqHz2x9r+mOOv4BfNH5P7tf/L4jolph+IFyuK55rvWcSw8wWJPfvRMQkF6ZIkrmW/cgomEbhZkzCOS4Md//u9wPNSXaQj+KH2LOfMiJWajeHCh4LKEC2X8PmBkMMpqoPpxtNFOPipiSFSL6BBF1a/3WMiSHHQFyPhfw44JiH7qbAFLdG4GjsAxXB8hBmaee29T2nvYY2GC4tWNvC10Wb1rTbKgw4TjJrOuXH+IG8WqsLhYwQG030oB77sxOP5DRapD4NqsOoRN39NCkggQOpAXFNDOPCWU006yZFoQH7SVd79iukn2ttqOUUT8z38ruTx6LReggm5RztCD4pAywC+AqaAk2CMfL9DNevCW6zBmh1/klR3/IWGBAJM74Tvs3Q2VjuGLcfL4DKDHkYX6a48TYzRA6Mi0q81PSQDAMwbwnpK+aSjZ0drkJbHhFYpr96wX7Oo6rIBGNbJc2UaTEz0QNsH5KLVbVkxKbP/xRpl9PiXkREJJJLvDoB3z7TBBkb/QJIGxOXIGSUFR+wTyA/rqn9GmdIp058WaPsZj4LO70+cFSmi4M9wOAoVhJcDXnfN7cKiQpRO6tGSEs2XGrrtfnFlP9Qc0a0Ac63ACjB4pD79InqonYpamioOaSa2OOSg7AGxDT6d1Ci5oRPrhb8AUkRRA8n4=
