#!/bin/sh

curl -ik -X POST "https://graph.facebook.com/v2.6/me/subscribed_apps?access_token=EAATlCTri1NoBANfXM5nCoHN9sYoBuOVFCNGlnZAOcZBaRH3vV9z46oEEbwbDFeAYrNWROOH1GZARcDcoVPI40BOUSWGYyfCIkBf9HQ7oN0p7rX2iW3uGbjGq8Tw3ZCfXJnDxZAC9rVFGrtlz9BLncecEnbZAQoEALQa2MnU9mPOwZDZD"